### ISSUE TITLE
pc지킴이 프로젝트에 기능을 추가하는 것이 좋다고 생각합니다

### ISSUE THREAD

**Issue by yeji0407** [hamonikr/hamonikr-pcchecker#3]
안녕하세요, 하모니카 os 에서 pc 지킴이 서비스를 유용하게 쓰고 있는 사용자입니다.
이 서비스를 다른 개방형 os 에서도 실행할 수 있도록 호환성을 향상시키고, 알람 기능, 배너 기능 등을 추가하면 더 좋은 프로그램이 될 것 같습니다.
pc지킴이 서비스를 활용해서 저희가 프로젝트를 개작해도 괜찮을까요?
혹시 계획하고 계셨던 추가 기능이나 희망하시는 추가 기능이 있다면 알려주세요.

**Comment by LukeHan1128** [comment]
좋은 의견 감사합니다. 
프로그램이 개선되는 방향이라면 개작은 환영입니다.

현재 하모니카 PC 지킴이(hamonikr pc checker)는 하모니카 OS에 맞춰 제작되어 있습니다. 의견 주신 타 개방형 OS에서 PC지킴이 사용이 가능하다면 개방형 OS 사용자에게 관리의 편의성을 제공해 줄 수 있겠네요.


현재 개선 및 추가 필요한 내용은 다음과 같습니다.
 - GUI 개선
 - 위험 상태인 경우 일정 주기로 사용자에게 알림을 전달
 - 사용자가 OS 로그인시 프로그램 자동 실행
 - 사용자 설정시 바탕화면에 보안상태 정보를 출력
 - 타 OS 지원

개선 진행중 문의사항 발생시 이슈 등록해 주시면 지원해 드리도록 하겠습니다.
