### ISSUE TITLE
비밀번호 접근 오류에 관해 질문드립니다.

### ISSUE THREAD

**Issue by RyuSeohyeon16** [hamonikr/hamonikr-pcchecker#4]
pcchecker에서 비밀번호를 변경한지 얼마나 되었는지와 비밀번호 설정에 접근 할 때 모두 사용자 계정이 아닌 root 계정의 정보를 가져오는 문제가 있어서 이를 해결하려고 합니다. 
저희 생각엔 cmd창에서 sudo passwd -S $USER | awk '{print $3}를 입력하면 비밀번호를 입력하게 유도된 뒤 제대로 현재 사용자 계정에 접근되는데 어플리케이션으로 접근하면 권한이 없으므로 root 계정의 정보를 가져와서 이런 문제가 발생하는 것 같습니다.
이 오류를 해결하려면 어떻게 권한을 받을 수 있을지 원작자님의 의견을 묻고싶습니다.

**Comment by LukeHan1128** [comment]
현재 프로그램 실행시 /usr/bin/pcchecker_asroot 를 실행하여 관리자 권한으로 /usr/bin/pcchecker 를 실행하도록 되어 있습니다.

따라서 /usr/bin/pcchecker_asroot 에서 사용자 정보를 /usr/bin/pcchecker 로 전달하도록 구성한 뒤 /usr/bin/pcchecker 에서 사용자 정보를 사용하는 부분을 변경 적용하면 가능합니다.

**Comment by LukeHan1128** [comment]
/usr/bin/pcchecker_asroot 을 아래와 같이 수정하여 사용자 정보를 PCCHECKER_USER 변수로 전달해 주시기 바랍니다.

`pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY PCCHECKER_USER=$USER QT_X11_NO_MITSHM=1 pcchecker`


/usr/bin/pcchecker 을 아래와 같이 수정하여 사용자 권한으로 실행하도록 변경해 보세요.

pw_date = subprocess.check_output("sudo passwd -S $PCCHECKER_USER | awk '{print $3}'", shell=True).decode().split('/')

subprocess.call ('su - $PCCHECKER_USER -c "cinnamon-settings user"', shell=True)

해당 이슈는 코드 변경 적용이 완료되면 종료 처리하도록 하겠습니다.

**Comment by RyuSeohyeon16** [comment]
알려주신 방법을 활용하여 위 문제를 해결하였고 설치시 이상없이 유저정보로 출력됨을 확인했습니다,

**Comment by LukeHan1128** [comment]
#5 
해당 이슈를 반영한 pull request 를 반영하여 해당 이슈는 종료 처리 하겠습니다.
