### ISSUE TITLE
다시 검사하기 버튼 클릭 시

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonikr-pcchecker#7]
아래 화면의 버튼을 누르면 어떻게 동작하는지 상태를 알 수 없습니다.

![pcchecker-error](https://user-images.githubusercontent.com/405502/91576829-d3673c80-e982-11ea-8b70-f9ecb958e27b.png)

버튼을 누르면 어떤 작업을 하는지, 그리고 얼마나 걸려서 끝나게 되는건지 이런게 필요하지 않을까요?

**Comment by yeji0407** [comment]
좋은 의견 감사합니다! 해당 사항을 보완하기 위해 버튼을 아이콘 이미지로 변경하고 툴팁을 통해 설명을 추가했습니다. 아래의 레포지토리에서 변경사항을 확인하실수 있습니다.
https://github.com/2020-Invesum-Internship/hamonikr-pcchecker
